### ISSUE TITLE
Feature: Remove one session instead of all 

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/Session-resurrection#4]
Add an option to remove just one selected session from the list (both from the local storage and the html)

**Comment by 3sne** [comment]
@TheAdnan, I discovered the extension recently, and I found it helpful! I would love to contribute to the extension. If you don't mind, I can try to take on this issue.

**Comment by 3sne** [comment]
PR for this feature is Open [here](https://github.com/TheAdnan/Session-resurrection/pull/10).
