### ISSUE TITLE
Restore session in new/current window

### ISSUE THREAD

**Issue by muesli** [TheAdnan/Session-resurrection#6]
Currently it seems to always restore the session in the first Firefox window I opened.

**Comment by TheAdnan** [comment]
Yeah, it was kinda planned that way, but I'll also add an option to open the session in a new window. Thanks for the suggestion!

**Comment by muesli** [comment]
I think the most confusing part is that it's currently opening the tabs in an entirley different Firefox window, even if I click it in a new/empty window.

**Comment by TheAdnan** [comment]
I figured out where the issue was, the add-on took the first opened Firefox window ID and that was a `const`, so that's why any session in any other window you tried to open, opened in that first Firefox window. I've fixed that, be sure to update the add-on. Thanks again!
