### ISSUE TITLE
Sessions no longer save?

### ISSUE THREAD

**Issue by Djinnistorm** [TheAdnan/Session-resurrection#8]
Was working well, but for some reason currently cannot save Sessions. Doing so creates a saved session, until you close the addon's console and open it again. Once you do this, the previously saved session is gone. Any ideas to troubleshoot?

**Comment by TheAdnan** [comment]
I'll look into it, someone reported the same issue and I'm trying to replicate that same bug. I'll let ya know once its fixed.

**Comment by TheAdnan** [comment]
Could you update the add-on to the last version and try to replicate that bug. Let me know if it works.

**Comment by Djinnistorm** [comment]
It does not seem to be working still, sorry.

**Comment by TheAdnan** [comment]
Which OS and Firefox version are you using?

**Comment by Djinnistorm** [comment]
Firefox 59.0.2 64 bit, Windows 8.1
