### ISSUE TITLE
Is there a way to save all tabs from all windows, instead of just the current window?

### ISSUE THREAD

**Issue by Saganus** [TheAdnan/Session-resurrection#9]
Not sure where to post this since I'm not sure if it's an issue or a feature request :)

Is there a way to save all tabs from their respective windows in a single session? 

I.e. something similar to the "Restore previous session" functionality that comes by default with Firefox.

**Comment by TheAdnan** [comment]
I haven't thought of that at all, but it's a good suggestion :smile_cat: 
You can take up the task if you want to?

**Comment by Saganus** [comment]
I will try!

Never wrote an extension before but one can learn :)

**Comment by 3sne** [comment]
Since @Saganus seems to be inactive, I would like to try the fix. PR for this issue is open: #11
